// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.titanclone.titan_clone.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Represents an installed app on the device.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InstalledApp (
  val packageName: String,
  val appName: String,
  val iconPath: String? = null,
  val versionName: String? = null,
  val versionCode: Long? = null,
  val isSystemApp: Boolean,
  val installedSizeBytes: Long? = null,
  val isSplitApk: Boolean,
  val category: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InstalledApp {
      val packageName = pigeonVar_list[0] as String
      val appName = pigeonVar_list[1] as String
      val iconPath = pigeonVar_list[2] as String?
      val versionName = pigeonVar_list[3] as String?
      val versionCode = pigeonVar_list[4] as Long?
      val isSystemApp = pigeonVar_list[5] as Boolean
      val installedSizeBytes = pigeonVar_list[6] as Long?
      val isSplitApk = pigeonVar_list[7] as Boolean
      val category = pigeonVar_list[8] as String?
      return InstalledApp(packageName, appName, iconPath, versionName, versionCode, isSystemApp, installedSizeBytes, isSplitApk, category)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      appName,
      iconPath,
      versionName,
      versionCode,
      isSystemApp,
      installedSizeBytes,
      isSplitApk,
      category,
    )
  }
}

/**
 * Represents a clone instance.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CloneInfo (
  val id: String,
  val packageName: String,
  val appName: String,
  val userId: Long,
  val status: String,
  val createdAtMs: Long,
  val profileJson: String? = null,
  val appIconPath: String? = null,
  val memoryUsageMb: Long? = null,
  val lastLaunchedMs: Long? = null,
  val storageSizeBytes: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CloneInfo {
      val id = pigeonVar_list[0] as String
      val packageName = pigeonVar_list[1] as String
      val appName = pigeonVar_list[2] as String
      val userId = pigeonVar_list[3] as Long
      val status = pigeonVar_list[4] as String
      val createdAtMs = pigeonVar_list[5] as Long
      val profileJson = pigeonVar_list[6] as String?
      val appIconPath = pigeonVar_list[7] as String?
      val memoryUsageMb = pigeonVar_list[8] as Long?
      val lastLaunchedMs = pigeonVar_list[9] as Long?
      val storageSizeBytes = pigeonVar_list[10] as Long?
      return CloneInfo(id, packageName, appName, userId, status, createdAtMs, profileJson, appIconPath, memoryUsageMb, lastLaunchedMs, storageSizeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      packageName,
      appName,
      userId,
      status,
      createdAtMs,
      profileJson,
      appIconPath,
      memoryUsageMb,
      lastLaunchedMs,
      storageSizeBytes,
    )
  }
}

/**
 * Represents a virtual device profile.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceProfile (
  val id: String,
  val name: String,
  val model: String,
  val brand: String,
  val manufacturer: String,
  val fingerprint: String,
  val screenDensity: Long,
  val screenWidth: Long,
  val screenHeight: Long,
  val sdkVersion: Long,
  val releaseVersion: String,
  val androidId: String,
  val imei: String,
  val macAddress: String,
  val bluetoothMac: String,
  val gsfId: String,
  val advertisingId: String,
  val serialNumber: String? = null,
  val timezone: String? = null,
  val locale: String? = null,
  val proxyHost: String? = null,
  val proxyPort: Long? = null,
  val proxyType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceProfile {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val model = pigeonVar_list[2] as String
      val brand = pigeonVar_list[3] as String
      val manufacturer = pigeonVar_list[4] as String
      val fingerprint = pigeonVar_list[5] as String
      val screenDensity = pigeonVar_list[6] as Long
      val screenWidth = pigeonVar_list[7] as Long
      val screenHeight = pigeonVar_list[8] as Long
      val sdkVersion = pigeonVar_list[9] as Long
      val releaseVersion = pigeonVar_list[10] as String
      val androidId = pigeonVar_list[11] as String
      val imei = pigeonVar_list[12] as String
      val macAddress = pigeonVar_list[13] as String
      val bluetoothMac = pigeonVar_list[14] as String
      val gsfId = pigeonVar_list[15] as String
      val advertisingId = pigeonVar_list[16] as String
      val serialNumber = pigeonVar_list[17] as String?
      val timezone = pigeonVar_list[18] as String?
      val locale = pigeonVar_list[19] as String?
      val proxyHost = pigeonVar_list[20] as String?
      val proxyPort = pigeonVar_list[21] as Long?
      val proxyType = pigeonVar_list[22] as String?
      return DeviceProfile(id, name, model, brand, manufacturer, fingerprint, screenDensity, screenWidth, screenHeight, sdkVersion, releaseVersion, androidId, imei, macAddress, bluetoothMac, gsfId, advertisingId, serialNumber, timezone, locale, proxyHost, proxyPort, proxyType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      model,
      brand,
      manufacturer,
      fingerprint,
      screenDensity,
      screenWidth,
      screenHeight,
      sdkVersion,
      releaseVersion,
      androidId,
      imei,
      macAddress,
      bluetoothMac,
      gsfId,
      advertisingId,
      serialNumber,
      timezone,
      locale,
      proxyHost,
      proxyPort,
      proxyType,
    )
  }
}

/**
 * Storage information for a clone.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StorageInfo (
  val cloneId: String,
  val totalSizeBytes: Long,
  val dataSizeBytes: Long,
  val cacheSizeBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageInfo {
      val cloneId = pigeonVar_list[0] as String
      val totalSizeBytes = pigeonVar_list[1] as Long
      val dataSizeBytes = pigeonVar_list[2] as Long
      val cacheSizeBytes = pigeonVar_list[3] as Long
      return StorageInfo(cloneId, totalSizeBytes, dataSizeBytes, cacheSizeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cloneId,
      totalSizeBytes,
      dataSizeBytes,
      cacheSizeBytes,
    )
  }
}

/**
 * Engine status information.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EngineStatus (
  val initialized: Boolean,
  val runningCloneCount: Long,
  val totalCloneCount: Long,
  val memoryUsageMb: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EngineStatus {
      val initialized = pigeonVar_list[0] as Boolean
      val runningCloneCount = pigeonVar_list[1] as Long
      val totalCloneCount = pigeonVar_list[2] as Long
      val memoryUsageMb = pigeonVar_list[3] as Long
      return EngineStatus(initialized, runningCloneCount, totalCloneCount, memoryUsageMb)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      initialized,
      runningCloneCount,
      totalCloneCount,
      memoryUsageMb,
    )
  }
}

/**
 * GMS availability state.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GmsState (
  val gmsAvailable: Boolean,
  val gmsVersion: String? = null,
  val playStoreVersion: String? = null,
  val gsfAvailable: Boolean,
  val maxPlayStoreClones: Long,
  val activePlayStoreClones: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GmsState {
      val gmsAvailable = pigeonVar_list[0] as Boolean
      val gmsVersion = pigeonVar_list[1] as String?
      val playStoreVersion = pigeonVar_list[2] as String?
      val gsfAvailable = pigeonVar_list[3] as Boolean
      val maxPlayStoreClones = pigeonVar_list[4] as Long
      val activePlayStoreClones = pigeonVar_list[5] as Long
      return GmsState(gmsAvailable, gmsVersion, playStoreVersion, gsfAvailable, maxPlayStoreClones, activePlayStoreClones)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      gmsAvailable,
      gmsVersion,
      playStoreVersion,
      gsfAvailable,
      maxPlayStoreClones,
      activePlayStoreClones,
    )
  }
}

/**
 * Device compatibility report.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CompatReport (
  val apiLevel: Long,
  val androidVersion: String,
  val isSupported: Boolean,
  val issues: List<String>,
  val missingPermissions: List<String>,
  val recommendations: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompatReport {
      val apiLevel = pigeonVar_list[0] as Long
      val androidVersion = pigeonVar_list[1] as String
      val isSupported = pigeonVar_list[2] as Boolean
      val issues = pigeonVar_list[3] as List<String>
      val missingPermissions = pigeonVar_list[4] as List<String>
      val recommendations = pigeonVar_list[5] as List<String>
      return CompatReport(apiLevel, androidVersion, isSupported, issues, missingPermissions, recommendations)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiLevel,
      androidVersion,
      isSupported,
      issues,
      missingPermissions,
      recommendations,
    )
  }
}

/**
 * Battery optimization info.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BatteryInfo (
  val isIgnoringOptimization: Boolean,
  val oemBrand: String,
  val oemIssue: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatteryInfo {
      val isIgnoringOptimization = pigeonVar_list[0] as Boolean
      val oemBrand = pigeonVar_list[1] as String
      val oemIssue = pigeonVar_list[2] as String?
      return BatteryInfo(isIgnoringOptimization, oemBrand, oemIssue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isIgnoringOptimization,
      oemBrand,
      oemIssue,
    )
  }
}

/**
 * Memory snapshot from the optimization layer.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MemorySnapshot (
  val totalDeviceRamMb: Long,
  val availableRamMb: Long,
  val engineNativeHeapMb: Long,
  val engineJavaHeapMb: Long,
  val cloneProcessCount: Long,
  val estimatedCloneOverheadMb: Long,
  val isLowMemory: Boolean,
  val recommendedMaxClones: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MemorySnapshot {
      val totalDeviceRamMb = pigeonVar_list[0] as Long
      val availableRamMb = pigeonVar_list[1] as Long
      val engineNativeHeapMb = pigeonVar_list[2] as Long
      val engineJavaHeapMb = pigeonVar_list[3] as Long
      val cloneProcessCount = pigeonVar_list[4] as Long
      val estimatedCloneOverheadMb = pigeonVar_list[5] as Long
      val isLowMemory = pigeonVar_list[6] as Boolean
      val recommendedMaxClones = pigeonVar_list[7] as Long
      return MemorySnapshot(totalDeviceRamMb, availableRamMb, engineNativeHeapMb, engineJavaHeapMb, cloneProcessCount, estimatedCloneOverheadMb, isLowMemory, recommendedMaxClones)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalDeviceRamMb,
      availableRamMb,
      engineNativeHeapMb,
      engineJavaHeapMb,
      cloneProcessCount,
      estimatedCloneOverheadMb,
      isLowMemory,
      recommendedMaxClones,
    )
  }
}

/**
 * Security check result.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SecurityStatus (
  val signatureValid: Boolean,
  val debuggerAttached: Boolean,
  val deviceRooted: Boolean,
  val isEmulator: Boolean,
  val nativeLibsIntact: Boolean,
  val overallSecure: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SecurityStatus {
      val signatureValid = pigeonVar_list[0] as Boolean
      val debuggerAttached = pigeonVar_list[1] as Boolean
      val deviceRooted = pigeonVar_list[2] as Boolean
      val isEmulator = pigeonVar_list[3] as Boolean
      val nativeLibsIntact = pigeonVar_list[4] as Boolean
      val overallSecure = pigeonVar_list[5] as Boolean
      return SecurityStatus(signatureValid, debuggerAttached, deviceRooted, isEmulator, nativeLibsIntact, overallSecure)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      signatureValid,
      debuggerAttached,
      deviceRooted,
      isEmulator,
      nativeLibsIntact,
      overallSecure,
    )
  }
}

/**
 * Performance metrics.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PerformanceMetrics (
  val avgColdLaunchMs: Long,
  val avgWarmLaunchMs: Long,
  val avgProfileLoadMs: Long,
  val totalLaunches: Long,
  val batteryLevel: Long,
  val isCharging: Boolean,
  val powerRecommendation: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PerformanceMetrics {
      val avgColdLaunchMs = pigeonVar_list[0] as Long
      val avgWarmLaunchMs = pigeonVar_list[1] as Long
      val avgProfileLoadMs = pigeonVar_list[2] as Long
      val totalLaunches = pigeonVar_list[3] as Long
      val batteryLevel = pigeonVar_list[4] as Long
      val isCharging = pigeonVar_list[5] as Boolean
      val powerRecommendation = pigeonVar_list[6] as String
      return PerformanceMetrics(avgColdLaunchMs, avgWarmLaunchMs, avgProfileLoadMs, totalLaunches, batteryLevel, isCharging, powerRecommendation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      avgColdLaunchMs,
      avgWarmLaunchMs,
      avgProfileLoadMs,
      totalLaunches,
      batteryLevel,
      isCharging,
      powerRecommendation,
    )
  }
}
private open class CloneApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstalledApp.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CloneInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceProfile.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EngineStatus.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GmsState.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompatReport.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatteryInfo.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MemorySnapshot.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SecurityStatus.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PerformanceMetrics.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InstalledApp -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CloneInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DeviceProfile -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is StorageInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is EngineStatus -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is GmsState -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CompatReport -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is BatteryInfo -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is MemorySnapshot -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is SecurityStatus -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is PerformanceMetrics -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API — Dart calls into native Android code.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CloneEngineApi {
  /** Initialize the virtualization engine. */
  fun initializeEngine(callback: (Result<Boolean>) -> Unit)
  /** Check if the engine is ready. */
  fun isEngineReady(): Boolean
  /** Get engine status information. */
  fun getEngineStatus(): EngineStatus
  /** Get all installed apps available for cloning. */
  fun getInstalledApps(callback: (Result<List<InstalledApp>>) -> Unit)
  /** Create a new clone of an app. */
  fun createClone(packageName: String, userId: Long, profilePreset: String?, callback: (Result<CloneInfo>) -> Unit)
  /** Launch a clone. */
  fun launchClone(cloneId: String, callback: (Result<Boolean>) -> Unit)
  /** Stop a running clone. */
  fun stopClone(cloneId: String, callback: (Result<Boolean>) -> Unit)
  /** Delete a clone and its data. */
  fun deleteClone(cloneId: String, callback: (Result<Boolean>) -> Unit)
  /** Get all created clones. */
  fun getClones(callback: (Result<List<CloneInfo>>) -> Unit)
  /** Get the status of a specific clone. */
  fun getCloneStatus(cloneId: String, callback: (Result<String>) -> Unit)
  /** Get virtual profile for a clone. */
  fun getCloneProfile(cloneId: String, callback: (Result<DeviceProfile?>) -> Unit)
  /** Update virtual profile for a clone. */
  fun updateProfile(cloneId: String, profile: DeviceProfile, callback: (Result<Boolean>) -> Unit)
  /** Reset virtual profile to new random values. */
  fun resetCloneProfile(cloneId: String, callback: (Result<DeviceProfile>) -> Unit)
  /** Get storage info for a clone. */
  fun getCloneStorageInfo(cloneId: String, callback: (Result<StorageInfo>) -> Unit)
  /** Clear a clone's cache. */
  fun clearCloneCache(cloneId: String, callback: (Result<Boolean>) -> Unit)
  /** Clear a clone's data (factory reset the clone). */
  fun clearCloneData(cloneId: String, callback: (Result<Boolean>) -> Unit)
  /** Set the maximum number of concurrent running clones. */
  fun setMaxConcurrentClones(maxClones: Long): Boolean
  /** Set memory limit per clone in MB. */
  fun setMemoryLimitPerClone(limitMb: Long): Boolean
  /** Get GMS availability state. */
  fun getGmsState(): GmsState
  /** Create a Play Store clone with device preset. */
  fun createPlayStoreClone(devicePreset: String?, callback: (Result<String?>) -> Unit)
  /** Delete a Play Store clone. */
  fun deletePlayStoreClone(cloneId: String, callback: (Result<Boolean>) -> Unit)
  /** Check device compatibility. */
  fun checkCompatibility(): CompatReport
  /** Get battery optimization info. */
  fun getBatteryOptimizationInfo(): BatteryInfo
  /** Start foreground service. */
  fun startForegroundService(runningCount: Long)
  /** Stop foreground service. */
  fun stopForegroundService()
  /** Get memory snapshot. */
  fun getMemorySnapshot(): MemorySnapshot
  /** Run security check. */
  fun performSecurityCheck(): SecurityStatus
  /** Get performance metrics. */
  fun getPerformanceMetrics(): PerformanceMetrics
  /** Check if it's safe to launch another clone. */
  fun canLaunchClone(): Boolean
  /** Request garbage collection. */
  fun requestGc()
  /** Encrypt clone data. */
  fun encryptCloneData(cloneId: String, callback: (Result<Boolean>) -> Unit)
  /** Securely delete clone data. */
  fun secureDeleteCloneData(cloneId: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by CloneEngineApi. */
    val codec: MessageCodec<Any?> by lazy {
      CloneApiPigeonCodec()
    }
    /** Sets up an instance of `CloneEngineApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CloneEngineApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.initializeEngine$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initializeEngine{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.isEngineReady$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isEngineReady())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getEngineStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getEngineStatus())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getInstalledApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getInstalledApps{ result: Result<List<InstalledApp>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.createClone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val userIdArg = args[1] as Long
            val profilePresetArg = args[2] as String?
            api.createClone(packageNameArg, userIdArg, profilePresetArg) { result: Result<CloneInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.launchClone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.launchClone(cloneIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.stopClone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.stopClone(cloneIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.deleteClone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.deleteClone(cloneIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getClones$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getClones{ result: Result<List<CloneInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getCloneStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.getCloneStatus(cloneIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getCloneProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.getCloneProfile(cloneIdArg) { result: Result<DeviceProfile?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.updateProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            val profileArg = args[1] as DeviceProfile
            api.updateProfile(cloneIdArg, profileArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.resetCloneProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.resetCloneProfile(cloneIdArg) { result: Result<DeviceProfile> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getCloneStorageInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.getCloneStorageInfo(cloneIdArg) { result: Result<StorageInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.clearCloneCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.clearCloneCache(cloneIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.clearCloneData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.clearCloneData(cloneIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.setMaxConcurrentClones$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val maxClonesArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.setMaxConcurrentClones(maxClonesArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.setMemoryLimitPerClone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val limitMbArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.setMemoryLimitPerClone(limitMbArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getGmsState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getGmsState())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.createPlayStoreClone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val devicePresetArg = args[0] as String?
            api.createPlayStoreClone(devicePresetArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.deletePlayStoreClone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.deletePlayStoreClone(cloneIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.checkCompatibility$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.checkCompatibility())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getBatteryOptimizationInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBatteryOptimizationInfo())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.startForegroundService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val runningCountArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.startForegroundService(runningCountArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.stopForegroundService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopForegroundService()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getMemorySnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getMemorySnapshot())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.performSecurityCheck$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.performSecurityCheck())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.getPerformanceMetrics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPerformanceMetrics())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.canLaunchClone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.canLaunchClone())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.requestGc$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestGc()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.encryptCloneData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.encryptCloneData(cloneIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.titan_clone.CloneEngineApi.secureDeleteCloneData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cloneIdArg = args[0] as String
            api.secureDeleteCloneData(cloneIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API — native Android calls into Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class CloneEventApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CloneEventApi. */
    val codec: MessageCodec<Any?> by lazy {
      CloneApiPigeonCodec()
    }
  }
  /** Clone status changed. */
  fun onCloneStatusChanged(cloneIdArg: String, newStatusArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.titan_clone.CloneEventApi.onCloneStatusChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(cloneIdArg, newStatusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Clone installation progress (0-100). */
  fun onInstallProgress(cloneIdArg: String, progressPercentArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.titan_clone.CloneEventApi.onInstallProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(cloneIdArg, progressPercentArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Clone crashed or encountered an error. */
  fun onCloneError(cloneIdArg: String, errorMessageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.titan_clone.CloneEventApi.onCloneError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(cloneIdArg, errorMessageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Engine initialization complete. */
  fun onEngineInitialized(successArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.titan_clone.CloneEventApi.onEngineInitialized$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(successArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Memory warning when usage is high. */
  fun onMemoryWarning(totalUsedMbArg: Long, thresholdMbArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.titan_clone.CloneEventApi.onMemoryWarning$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(totalUsedMbArg, thresholdMbArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** GMS checkin completed for a clone. */
  fun onGmsCheckinComplete(cloneIdArg: String, successArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.titan_clone.CloneEventApi.onGmsCheckinComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(cloneIdArg, successArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Foreground service state changed. */
  fun onForegroundServiceStateChanged(runningArg: Boolean, cloneCountArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.titan_clone.CloneEventApi.onForegroundServiceStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(runningArg, cloneCountArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
